---
title: "Unit 03-01: Simple Linear Regression: Discovery & Model"
subtitle: "Class Resources"
format: 
  html:
    embed-resources: true
    toc: true
---



```{r setup}
#| include: false
knitr::opts_chunk$set(
  collapse = TRUE, 
  warning = FALSE,
  message = FALSE,
  error = TRUE,
  fig.height = 2.75, 
  fig.width = 4.25,
  fig.env = 'figure',
  fig.pos = 'h',
  fig.align = 'center')
```


Here you will find class resources for Unit 03-01: Simple Linear Regression: Discovery & Model, rendered version of this is posted in the [course website](https://mutasim221b.github.io/Mutasim-Personal-Course-2/) (Class Resources tab). You can also download the .qmd file [here](../activity_templates/03_04-slr-intro-formalization.qmd) and open in R-studio. 


# Notes

## Learning goals

By the end of this lesson, you should be able to:

- Visualize and describe the relationship between two **quantitative** variables using a **scatterplot**
- Describe/identify **weak**/**strong**, and **positive**/**negative** correlation from a point cloud
- Build intuition for fitting **lines** to quantify the relationship between two quantitative variables
- Differentiate between a **response**/**dependent variable** and a **independent**/**explanatory variable**
- Understand the relation between the **scatterplot** and **correlation coefficient**.
- Describe the strength and direction of the **linear** relationship between two quantitative variables using the correlation coefficient, including interpreting whether an association is weak or strong, and positive or negative.
- Write a **model formula** for a simple linear regression model with a quantitative predictor.
- Interpret the estimated **intercept** and **slope** coefficients in a simple linear regression model with a quantitative predictor
- Compute **predicted/fitted values** from a linear regression model formula
- Interpret predicted values in the context of the data





## Practice Problems

Practice problems are essential for your understanding, practice, and exploration. I will post the practice problems for Unit 03 after class (please look for my email!).



# Resources

## Handouts & Activities

- Download the [Unit 03-01 handouts](/Resources/Unit03_01_Handout.pdf) from here.
- Fun [Regression by eye](/Resources/regression-by-eye.ppt) activity!



# Correlation Coefficient (r)

We can quantify the **linear** relationship between two quantitative variables using a numerical summary known as **correlation coefficient** (sometimes known as a "correlation" or "Pearson's correlation"). Correlation can range from -1 to 1, where a correlation of 0 indicates that there is *no* linear relationship between the two quantitative variables.

::: {.callout-note}
A correlation close to zero, $r \approx 0$, does **not** rule out the possibility of a \textbf{nonlinear} relationship between two variables.
:::

Below is an example of a "Math Box". You'll see these occasionally throughout this course. You are *not* required to memorize (if in the quiz, formula will be provided!), anything in the math boxes. If you plan on *continuing* with Statistics courses (or are interested in the math behind everything!), these math boxes are for you!

::: {.callout-note collapse="true"}
## Math Box: Correlation Coefficient 
The correlation coefficient, $r_{x,y}$, can be written in terms of sums of squares and cross-products as:

$$
r = \frac{SS_{xy}}{\sqrt{SS_{xx}} \, \sqrt{SS_{yy}}} = \frac{\sum z_x z_y}{n - 1}
$$
Where, 
$$
SS_{xx} = \sum x^2 - \frac{(\sum x)^2}{n}, \newline
SS_{yy} = \sum y^2 - \frac{(\sum y)^2}{n}, \newline
SS_{xy} = \sum xy - \frac{(\sum x)(\sum y)}{n}
$$

:::

In general, we will want to be able to describe (qualitatively) two aspects of correlation:

1. Strength
- Is the correlation between x and y **strong**, or **weak**, i.e. how closely do the points fit around a line? This has to do with how **dispersed** our point clouds are.

2. Direction
- Is the correlation between x and y **positive** or **negative**, i.e. does y go "up" when x goes "up" (positive), or does y go "down" when x goes "up" (negative)?

Stronger correlations will be *further* from 0 (closer to -1 or 1), and *positive* and *negative* correlations will have the appropriate respective sign (above or below zero).



# Fitted (Least-Squares) Regression Line

The fitted (least-squares) regression line has the form:

$$
\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 X
$$
Here,  
- $\hat{\beta}_1$ is the estimated **slope**,  
- $\hat{\beta}_0$ is the estimated **intercept**.
An important property of the least-squares regression line is that it **always passes through the point** $(\bar{X}, \bar{Y})$.
 
::: {.callout-note collapse="true"}
## Math Box: Estmiated Slope and Intercept
The estimated slope and intercept can be computed as:

$$
\hat{\beta}_1 = \frac{r S_y}{S_x} = \frac{SS_{xy}}{SS_{xx}},
\qquad
\hat{\beta}_0 = \bar{Y} - \hat{\beta}_1 \bar{X}.
$$

:::



